# Generated by Django 2.2.11 on 2020-05-05 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20200505_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 15, 22, 47, 708790, tzinfo=utc)),
        ),
    ]
