# Generated by Django 2.2.11 on 2020-05-07 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_auto_20200505_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 13, 26, 45, 37606, tzinfo=utc)),
        ),
    ]
