# Generated by Django 2.2.11 on 2020-05-08 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_auto_20200507_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 9, 18, 23, 817158, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 9, 18, 23, 817158, tzinfo=utc)),
        ),
    ]
