# Generated by Django 2.2.11 on 2020-05-08 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_auto_20200508_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 9, 42, 59, 466111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 9, 42, 59, 466111, tzinfo=utc)),
        ),
    ]
