# Generated by Django 2.2.11 on 2020-05-08 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_auto_20200508_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=100)),
                ('solution', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 16, 37, 33, 724721, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 16, 37, 33, 723725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 16, 37, 33, 723725, tzinfo=utc)),
        ),
    ]
